// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axvckiayljhgvosrewrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4dmNraWF5bGpoZ3Zvc3Jld3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzA3NzgsImV4cCI6MjA2ODM0Njc3OH0.j6nUYUQ6KPjFYdxxlMVHa18haItStjH9BfaG5uBjNf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});